-- MySQL Script generated by MySQL Workbench
-- 04/05/17 10:49:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Contact` ;

CREATE TABLE IF NOT EXISTS `Contact` (
  `contact_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `address` VARCHAR(100) NULL,
  `phone` VARCHAR(10) NULL,
  `state` VARCHAR(2) NULL,
  `zipcode` VARCHAR(10) NULL,
  PRIMARY KEY (`contact_id`),
  INDEX `unique_identifier` (`first_name` ASC, `last_name` ASC, `phone` ASC, `state` ASC, `zipcode` ASC, `address` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Borrower_Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Borrower_Account` ;

CREATE TABLE IF NOT EXISTS `Borrower_Account` (
  `borrower_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Contact_contact_id` INT NOT NULL,
  PRIMARY KEY (`borrower_id`),
  INDEX `fk_Borrower_Account_Contact1_idx` (`Contact_contact_id` ASC),
  CONSTRAINT `fk_Borrower_Account_Contact1`
    FOREIGN KEY (`Contact_contact_id`)
    REFERENCES `Contact` (`contact_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Media` ;

CREATE TABLE IF NOT EXISTS `Media` (
  `UPC` VARCHAR(12) NULL,
  `title` VARCHAR(100) NOT NULL,
  `description` LONGTEXT NOT NULL,
  PRIMARY KEY (`UPC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Status` ;

CREATE TABLE IF NOT EXISTS `Status` (
  `status` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Media_Items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Media_Items` ;

CREATE TABLE IF NOT EXISTS `Media_Items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` LONGTEXT NOT NULL,
  `Media_UPC` VARCHAR(12) NOT NULL,
  `Status_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Media Items_Media1_idx` (`Media_UPC` ASC),
  INDEX `fk_Media Items_Status1_idx` (`Status_status` ASC),
  CONSTRAINT `fk_Media Items_Media1`
    FOREIGN KEY (`Media_UPC`)
    REFERENCES `Media` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Media Items_Status1`
    FOREIGN KEY (`Status_status`)
    REFERENCES `Status` (`status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TransactionType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransactionType` ;

CREATE TABLE IF NOT EXISTS `TransactionType` (
  `transaction_type` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NOT NULL,
  PRIMARY KEY (`transaction_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TransactionStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TransactionStatus` ;

CREATE TABLE IF NOT EXISTS `TransactionStatus` (
  `transaction_status` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NOT NULL,
  PRIMARY KEY (`transaction_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Transaction` ;

CREATE TABLE IF NOT EXISTS `Transaction` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `Borrower_Account_borrower_id` INT NOT NULL,
  `Media_Items_id` INT NOT NULL,
  `TransactionType_transaction_type` VARCHAR(45) NOT NULL,
  `TransactionStatus_transaction_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `fk_Transaction_with_history_Borrower_Account1_idx` (`Borrower_Account_borrower_id` ASC),
  INDEX `fk_Transaction_with_history_Media_Items1_idx` (`Media_Items_id` ASC),
  INDEX `fk_Transaction_with_history_TransactionType1_idx` (`TransactionType_transaction_type` ASC),
  INDEX `fk_Transaction_TransactionStatus1_idx` (`TransactionStatus_transaction_status` ASC),
  CONSTRAINT `fk_Transaction_with_history_Borrower_Account1`
    FOREIGN KEY (`Borrower_Account_borrower_id`)
    REFERENCES `Borrower_Account` (`borrower_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_with_history_Media Items1`
    FOREIGN KEY (`Media_Items_id`)
    REFERENCES `Media_Items` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_with_history_TransactionType1`
    FOREIGN KEY (`TransactionType_transaction_type`)
    REFERENCES `TransactionType` (`transaction_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_TransactionStatus1`
    FOREIGN KEY (`TransactionStatus_transaction_status`)
    REFERENCES `TransactionStatus` (`transaction_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CD` ;

CREATE TABLE IF NOT EXISTS `CD` (
  `UPC` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`UPC`),
  CONSTRAINT `fk_CD_Media1`
    FOREIGN KEY (`UPC`)
    REFERENCES `Media` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Book` ;

CREATE TABLE IF NOT EXISTS `Book` (
  `UPC` VARCHAR(12) NOT NULL,
  `ISBN` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`UPC`),
  UNIQUE INDEX `unique_identifier` (`ISBN` ASC),
  CONSTRAINT `fk_Book_Media1`
    FOREIGN KEY (`UPC`)
    REFERENCES `Media` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiskMovie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiskMovie` ;

CREATE TABLE IF NOT EXISTS `DiskMovie` (
  `UPC` VARCHAR(12) NOT NULL,
  `run_time` INT NULL,
  `release_date` DATE NULL,
  `number_of_discs` INT NULL,
  PRIMARY KEY (`UPC`),
  CONSTRAINT `fk_DiskMovie_Media1`
    FOREIGN KEY (`UPC`)
    REFERENCES `Media` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RateItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RateItem` ;

CREATE TABLE IF NOT EXISTS `RateItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` LONGTEXT NULL,
  `Transaction_transaction_id` INT NOT NULL,
  `stars` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_RateItem_Transaction1_idx` (`Transaction_transaction_id` ASC),
  CONSTRAINT `fk_RateItem_Transaction1`
    FOREIGN KEY (`Transaction_transaction_id`)
    REFERENCES `Transaction` (`transaction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnumGenre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnumGenre` ;

CREATE TABLE IF NOT EXISTS `EnumGenre` (
  `genre` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`genre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnumSubject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnumSubject` ;

CREATE TABLE IF NOT EXISTS `EnumSubject` (
  `subject` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`subject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnumAudience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnumAudience` ;

CREATE TABLE IF NOT EXISTS `EnumAudience` (
  `targeted_audience` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`targeted_audience`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnumLanguage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnumLanguage` ;

CREATE TABLE IF NOT EXISTS `EnumLanguage` (
  `language` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`language`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnumAspectRatio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnumAspectRatio` ;

CREATE TABLE IF NOT EXISTS `EnumAspectRatio` (
  `aspect_ratio` VARCHAR(45) NOT NULL,
  `aspect_ratio_description` LONGTEXT NULL,
  PRIMARY KEY (`aspect_ratio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Studio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Studio` ;

CREATE TABLE IF NOT EXISTS `Studio` (
  `studio` VARCHAR(45) NOT NULL,
  `studio_description` LONGTEXT NULL,
  PRIMARY KEY (`studio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnumFormat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnumFormat` ;

CREATE TABLE IF NOT EXISTS `EnumFormat` (
  `format` VARCHAR(45) NOT NULL,
  `format_description` LONGTEXT NULL,
  PRIMARY KEY (`format`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnumDiskType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnumDiskType` ;

CREATE TABLE IF NOT EXISTS `EnumDiskType` (
  `disk_type` VARCHAR(45) NOT NULL,
  `deskt_type_description` LONGTEXT NULL,
  PRIMARY KEY (`disk_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Review` ;

CREATE TABLE IF NOT EXISTS `Review` (
  `review` LONGTEXT NOT NULL,
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `rating` INT NULL,
  PRIMARY KEY (`review_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TrackTitle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackTitle` ;

CREATE TABLE IF NOT EXISTS `TrackTitle` (
  `track_id` INT NOT NULL AUTO_INCREMENT,
  `track_title` VARCHAR(45) NOT NULL,
  `track_run_time` INT NOT NULL,
  `track_background` LONGTEXT NOT NULL,
  PRIMARY KEY (`track_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Artist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Artist` ;

CREATE TABLE IF NOT EXISTS `Artist` (
  `artist_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `background` LONGTEXT NULL,
  PRIMARY KEY (`artist_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CD_has_EnumArtist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CD_has_EnumArtist` ;

CREATE TABLE IF NOT EXISTS `CD_has_EnumArtist` (
  `CD_UPC` VARCHAR(12) NOT NULL,
  `Artist_artist_id` INT NOT NULL,
  PRIMARY KEY (`CD_UPC`, `Artist_artist_id`),
  INDEX `fk_CD_has_EnumArtist_EnumArtist1_idx` (`Artist_artist_id` ASC),
  INDEX `fk_CD_has_EnumArtist_CD1_idx` (`CD_UPC` ASC),
  CONSTRAINT `fk_CD_has_EnumArtist_CD1`
    FOREIGN KEY (`CD_UPC`)
    REFERENCES `CD` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CD_has_EnumArtist_EnumArtist1`
    FOREIGN KEY (`Artist_artist_id`)
    REFERENCES `Artist` (`artist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Author` ;

CREATE TABLE IF NOT EXISTS `Author` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `background` LONGTEXT NULL,
  PRIMARY KEY (`author_id`),
  UNIQUE INDEX `unique_identifier` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CD_has_TrackTitle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CD_has_TrackTitle` ;

CREATE TABLE IF NOT EXISTS `CD_has_TrackTitle` (
  `CD_UPC` VARCHAR(12) NOT NULL,
  `TrackTitle_track_id` INT NOT NULL,
  PRIMARY KEY (`CD_UPC`, `TrackTitle_track_id`),
  INDEX `fk_CD_has_EnumTrackTitle_EnumTrackTitle1_idx` (`TrackTitle_track_id` ASC),
  INDEX `fk_CD_has_EnumTrackTitle_CD1_idx` (`CD_UPC` ASC),
  CONSTRAINT `fk_CD_has_EnumTrackTitle_CD1`
    FOREIGN KEY (`CD_UPC`)
    REFERENCES `CD` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CD_has_EnumTrackTitle_EnumTrackTitle1`
    FOREIGN KEY (`TrackTitle_track_id`)
    REFERENCES `TrackTitle` (`track_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Director` ;

CREATE TABLE IF NOT EXISTS `Director` (
  `director_id` INT NOT NULL AUTO_INCREMENT,
  `director_description` LONGTEXT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`director_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Actor` ;

CREATE TABLE IF NOT EXISTS `Actor` (
  `actor_name` VARCHAR(45) NOT NULL,
  `actor_description` LONGTEXT NULL,
  `actor_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`actor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EnumSubtitileLanguage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `EnumSubtitileLanguage` ;

CREATE TABLE IF NOT EXISTS `EnumSubtitileLanguage` (
  `language` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  PRIMARY KEY (`language`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RateBorrower`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RateBorrower` ;

CREATE TABLE IF NOT EXISTS `RateBorrower` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` LONGTEXT NULL,
  `Transaction_transaction_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_RateBorrower_Transaction1_idx` (`Transaction_transaction_id` ASC),
  CONSTRAINT `fk_RateBorrower_Transaction1`
    FOREIGN KEY (`Transaction_transaction_id`)
    REFERENCES `Transaction` (`transaction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Media_has_Review`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Media_has_Review` ;

CREATE TABLE IF NOT EXISTS `Media_has_Review` (
  `Media_UPC` VARCHAR(12) NOT NULL,
  `Review_review_id` INT NOT NULL,
  PRIMARY KEY (`Media_UPC`, `Review_review_id`),
  INDEX `fk_Media_has_Review_Review1_idx` (`Review_review_id` ASC),
  INDEX `fk_Media_has_Review_Media1_idx` (`Media_UPC` ASC),
  CONSTRAINT `fk_Media_has_Review_Media1`
    FOREIGN KEY (`Media_UPC`)
    REFERENCES `Media` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Media_has_Review_Review1`
    FOREIGN KEY (`Review_review_id`)
    REFERENCES `Review` (`review_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Book_has_Author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Book_has_Author` ;

CREATE TABLE IF NOT EXISTS `Book_has_Author` (
  `Book_UPC` VARCHAR(12) NOT NULL,
  `Author_author_id` INT NOT NULL,
  PRIMARY KEY (`Book_UPC`, `Author_author_id`),
  INDEX `fk_Book_has_Author_Author1_idx` (`Author_author_id` ASC),
  INDEX `fk_Book_has_Author_Book1_idx` (`Book_UPC` ASC),
  CONSTRAINT `fk_Book_has_Author_Book1`
    FOREIGN KEY (`Book_UPC`)
    REFERENCES `Book` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_has_Author_Author1`
    FOREIGN KEY (`Author_author_id`)
    REFERENCES `Author` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiskMovie_has_Studio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiskMovie_has_Studio` ;

CREATE TABLE IF NOT EXISTS `DiskMovie_has_Studio` (
  `DiskMovie_UPC` VARCHAR(12) NOT NULL,
  `Studio_studio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DiskMovie_UPC`, `Studio_studio`),
  INDEX `fk_DiskMovie_has_Studio_Studio1_idx` (`Studio_studio` ASC),
  INDEX `fk_DiskMovie_has_Studio_DiskMovie1_idx` (`DiskMovie_UPC` ASC),
  CONSTRAINT `fk_DiskMovie_has_Studio_DiskMovie1`
    FOREIGN KEY (`DiskMovie_UPC`)
    REFERENCES `DiskMovie` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DiskMovie_has_Studio_Studio1`
    FOREIGN KEY (`Studio_studio`)
    REFERENCES `Studio` (`studio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiskMovie_has_Actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiskMovie_has_Actor` ;

CREATE TABLE IF NOT EXISTS `DiskMovie_has_Actor` (
  `DiskMovie_UPC` VARCHAR(12) NOT NULL,
  `Actor_actor_id` INT NOT NULL,
  PRIMARY KEY (`DiskMovie_UPC`, `Actor_actor_id`),
  INDEX `fk_DiskMovie_has_Actor_Actor1_idx` (`Actor_actor_id` ASC),
  INDEX `fk_DiskMovie_has_Actor_DiskMovie1_idx` (`DiskMovie_UPC` ASC),
  CONSTRAINT `fk_DiskMovie_has_Actor_DiskMovie1`
    FOREIGN KEY (`DiskMovie_UPC`)
    REFERENCES `DiskMovie` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DiskMovie_has_Actor_Actor1`
    FOREIGN KEY (`Actor_actor_id`)
    REFERENCES `Actor` (`actor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Media_has_EnumLanguage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Media_has_EnumLanguage` ;

CREATE TABLE IF NOT EXISTS `Media_has_EnumLanguage` (
  `Media_UPC` VARCHAR(12) NOT NULL,
  `EnumLanguage_language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Media_UPC`, `EnumLanguage_language`),
  INDEX `fk_Media_has_EnumLanguage_EnumLanguage1_idx` (`EnumLanguage_language` ASC),
  INDEX `fk_Media_has_EnumLanguage_Media1_idx` (`Media_UPC` ASC),
  CONSTRAINT `fk_Media_has_EnumLanguage_Media1`
    FOREIGN KEY (`Media_UPC`)
    REFERENCES `Media` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Media_has_EnumLanguage_EnumLanguage1`
    FOREIGN KEY (`EnumLanguage_language`)
    REFERENCES `EnumLanguage` (`language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Media_has_EnumSubject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Media_has_EnumSubject` ;

CREATE TABLE IF NOT EXISTS `Media_has_EnumSubject` (
  `Media_UPC` VARCHAR(12) NOT NULL,
  `EnumSubject_subject` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Media_UPC`, `EnumSubject_subject`),
  INDEX `fk_Media_has_EnumSubject_EnumSubject1_idx` (`EnumSubject_subject` ASC),
  INDEX `fk_Media_has_EnumSubject_Media1_idx` (`Media_UPC` ASC),
  CONSTRAINT `fk_Media_has_EnumSubject_Media1`
    FOREIGN KEY (`Media_UPC`)
    REFERENCES `Media` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Media_has_EnumSubject_EnumSubject1`
    FOREIGN KEY (`EnumSubject_subject`)
    REFERENCES `EnumSubject` (`subject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Media_has_EnumAudience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Media_has_EnumAudience` ;

CREATE TABLE IF NOT EXISTS `Media_has_EnumAudience` (
  `Media_UPC` VARCHAR(12) NOT NULL,
  `EnumAudience_targeted_audience` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Media_UPC`, `EnumAudience_targeted_audience`),
  INDEX `fk_Media_has_EnumAudience_EnumAudience1_idx` (`EnumAudience_targeted_audience` ASC),
  INDEX `fk_Media_has_EnumAudience_Media1_idx` (`Media_UPC` ASC),
  CONSTRAINT `fk_Media_has_EnumAudience_Media1`
    FOREIGN KEY (`Media_UPC`)
    REFERENCES `Media` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Media_has_EnumAudience_EnumAudience1`
    FOREIGN KEY (`EnumAudience_targeted_audience`)
    REFERENCES `EnumAudience` (`targeted_audience`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Media_has_EnumGenre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Media_has_EnumGenre` ;

CREATE TABLE IF NOT EXISTS `Media_has_EnumGenre` (
  `Media_UPC` VARCHAR(12) NOT NULL,
  `EnumGenre_genre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Media_UPC`, `EnumGenre_genre`),
  INDEX `fk_Media_has_EnumGenre_EnumGenre1_idx` (`EnumGenre_genre` ASC),
  INDEX `fk_Media_has_EnumGenre_Media1_idx` (`Media_UPC` ASC),
  CONSTRAINT `fk_Media_has_EnumGenre_Media1`
    FOREIGN KEY (`Media_UPC`)
    REFERENCES `Media` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Media_has_EnumGenre_EnumGenre1`
    FOREIGN KEY (`EnumGenre_genre`)
    REFERENCES `EnumGenre` (`genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiskMovie_has_EnumSubtitileLanguage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiskMovie_has_EnumSubtitileLanguage` ;

CREATE TABLE IF NOT EXISTS `DiskMovie_has_EnumSubtitileLanguage` (
  `DiskMovie_UPC` VARCHAR(12) NOT NULL,
  `EnumSubtitileLanguage_language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DiskMovie_UPC`, `EnumSubtitileLanguage_language`),
  INDEX `fk_DiskMovie_has_EnumSubtitileLanguage_EnumSubtitileLanguag_idx` (`EnumSubtitileLanguage_language` ASC),
  INDEX `fk_DiskMovie_has_EnumSubtitileLanguage_DiskMovie1_idx` (`DiskMovie_UPC` ASC),
  CONSTRAINT `fk_DiskMovie_has_EnumSubtitileLanguage_DiskMovie1`
    FOREIGN KEY (`DiskMovie_UPC`)
    REFERENCES `DiskMovie` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DiskMovie_has_EnumSubtitileLanguage_EnumSubtitileLanguage1`
    FOREIGN KEY (`EnumSubtitileLanguage_language`)
    REFERENCES `EnumSubtitileLanguage` (`language`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiskMovie_has_EnumAspectRatio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiskMovie_has_EnumAspectRatio` ;

CREATE TABLE IF NOT EXISTS `DiskMovie_has_EnumAspectRatio` (
  `DiskMovie_UPC` VARCHAR(12) NOT NULL,
  `EnumAspectRatio_aspect_ratio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DiskMovie_UPC`, `EnumAspectRatio_aspect_ratio`),
  INDEX `fk_DiskMovie_has_EnumAspectRatio_EnumAspectRatio1_idx` (`EnumAspectRatio_aspect_ratio` ASC),
  INDEX `fk_DiskMovie_has_EnumAspectRatio_DiskMovie1_idx` (`DiskMovie_UPC` ASC),
  CONSTRAINT `fk_DiskMovie_has_EnumAspectRatio_DiskMovie1`
    FOREIGN KEY (`DiskMovie_UPC`)
    REFERENCES `DiskMovie` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DiskMovie_has_EnumAspectRatio_EnumAspectRatio1`
    FOREIGN KEY (`EnumAspectRatio_aspect_ratio`)
    REFERENCES `EnumAspectRatio` (`aspect_ratio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiskMovie_has_EnumDiskType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiskMovie_has_EnumDiskType` ;

CREATE TABLE IF NOT EXISTS `DiskMovie_has_EnumDiskType` (
  `DiskMovie_UPC` VARCHAR(12) NOT NULL,
  `EnumDiskType_disk_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DiskMovie_UPC`, `EnumDiskType_disk_type`),
  INDEX `fk_DiskMovie_has_EnumDiskType_EnumDiskType1_idx` (`EnumDiskType_disk_type` ASC),
  INDEX `fk_DiskMovie_has_EnumDiskType_DiskMovie1_idx` (`DiskMovie_UPC` ASC),
  CONSTRAINT `fk_DiskMovie_has_EnumDiskType_DiskMovie1`
    FOREIGN KEY (`DiskMovie_UPC`)
    REFERENCES `DiskMovie` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DiskMovie_has_EnumDiskType_EnumDiskType1`
    FOREIGN KEY (`EnumDiskType_disk_type`)
    REFERENCES `EnumDiskType` (`disk_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiskMovie_has_EnumFormat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiskMovie_has_EnumFormat` ;

CREATE TABLE IF NOT EXISTS `DiskMovie_has_EnumFormat` (
  `DiskMovie_UPC` VARCHAR(12) NOT NULL,
  `EnumFormat_format` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DiskMovie_UPC`, `EnumFormat_format`),
  INDEX `fk_DiskMovie_has_EnumFormat_EnumFormat1_idx` (`EnumFormat_format` ASC),
  INDEX `fk_DiskMovie_has_EnumFormat_DiskMovie1_idx` (`DiskMovie_UPC` ASC),
  CONSTRAINT `fk_DiskMovie_has_EnumFormat_DiskMovie1`
    FOREIGN KEY (`DiskMovie_UPC`)
    REFERENCES `DiskMovie` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DiskMovie_has_EnumFormat_EnumFormat1`
    FOREIGN KEY (`EnumFormat_format`)
    REFERENCES `EnumFormat` (`format`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DiskMovie_has_Director`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DiskMovie_has_Director` ;

CREATE TABLE IF NOT EXISTS `DiskMovie_has_Director` (
  `DiskMovie_UPC` VARCHAR(12) NOT NULL,
  `Director_director_id` INT NOT NULL,
  PRIMARY KEY (`DiskMovie_UPC`, `Director_director_id`),
  INDEX `fk_DiskMovie_has_Director_Director1_idx` (`Director_director_id` ASC),
  INDEX `fk_DiskMovie_has_Director_DiskMovie1_idx` (`DiskMovie_UPC` ASC),
  CONSTRAINT `fk_DiskMovie_has_Director_DiskMovie1`
    FOREIGN KEY (`DiskMovie_UPC`)
    REFERENCES `DiskMovie` (`UPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DiskMovie_has_Director_Director1`
    FOREIGN KEY (`Director_director_id`)
    REFERENCES `Director` (`director_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
